name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: STAMP=$(date +%s) && docker build . --file Dockerfile --tag ghcr.io/acarling/ddns:$STAMP && docker push ghcr.io/acarling/ddns:$STAMP
